version: "3"

services:
  postgres:
    image: "postgres:12-alpine"
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: springfield-bank-dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: "pgadmin"
    image: "dpage/pgadmin4:4"
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "16543:80"
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:6-alpine
    command: redis-server --requirepass Redis2021!
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev: