version: "3"

services:
  springfield-bank-api:
    container_name: "go-springfield-bank"
    build:
      context: ..
    restart: unless-stopped
    environment:
      "LOG_ENCODING": json # json, console; default: json
      "LOG_LEVEL": info # trace, debug, info, warn, error, fatal, panic; default: info
      "HOST": localhost:8080 # The host + port the application will be exposed. default: localhost:8080
      "PORT": 8080 # the port the application will listen to (can be different from HOST). default: 8080
      "MONITORING_PORT": 8086 # The port the application will listen to metrics/health endpoints. MUST be different from PORT. default: 8086
      "DB_HOST": postgres # default: localhost
      "DB_PORT": 5432 # default: 5432
      "DB_NAME": springfield-bank
      "DB_USER": postgres
      "DB_PASSWORD": postgres
      "DB_SSL_MODE": prefer # default: prefer
      "DATABASE_URL": # Takes precedence over separated DB_* vars. https://www.postgresql.org/docs/10/libpq-connect.html#id-1.7.3.8.3.6. default: ""
      "DB_POOL_MAX_CONN": 5 # Max opened connections. default: 5
      "DB_POOL_MAX_CONN_LIFETIME": 5m # Max time a DB connection can live. default: 5m
      "DB_MIGRATE": "true" # Run DB migration on startup. default: true
      "REDIS_URL": redis://:Redis2021!@redis:6379 # default: redis://:Redis2021!@localhost:6379
      "AUTH_SECRET_KEY": "CHANGE-IT" # The secret key used to generate and validate JWT tokens. default: YOU-SHOULD-CHANGE-ME
      "AUTH_ACCESS_TOKEN_DURATION": 15m # How long the JWT access token is valid after issuing. default: 15m
    ports:
      - 8080:8080
      - 8086:8086
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/live" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: "postgres:12-alpine"
    command: ["postgres", "-c", "log_statement=all"]
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: springfield-bank
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    command: redis-server --requirepass Redis2021!
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: