run:
  timeout: 1m
  allow-parallel-runners: true

linters-settings:
  errcheck:
    exclude-functions:
      - (io.ReadCloser).Close
  goimports:
    local-prefixes: github.com/helder-jaspion/go-springfield-bank
  gofumpt:
    extra-rules: true
  gomnd:
    settings:
      mnd:
        ignored-numbers: 0, 1, 100
  gocyclo:
    min-complexity: 16
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: false # require machine-readable nolint directives (with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  tagliatelle:
    case:
      rules:
        json: snake

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - errorlint
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - dupl
    - typecheck
    - unused
    - varcheck
    - exportloopref
    - forcetypeassert
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofumpt
    - gomnd
    - goprintffuncname
    - gosec
    - ifshort
    - misspell
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unparam
    - whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - forcetypeassert
        - gocognit
        - goconst
        - gocyclo
        - gosec

    - path: test/e2e
      linters:
        - tparallel
