package model

import (
	"time"

	"github.com/google/uuid"
)

// TransferID represents a Transfer ID as uuid
type TransferID string

// NewTransferID returns a new TransferID with value generated by uuid.New()
func NewTransferID() TransferID {
	return TransferID(uuid.NewString())
}

// Transfer represents a bank transfer between two accounts.
type Transfer struct {
	ID                   TransferID
	AccountOriginID      AccountID
	AccountDestinationID AccountID
	Amount               Money
	CreatedAt            time.Time
}

// NewTransfer returns a new Transfer filled with the corresponding arguments with generated values for id and createdAt.
func NewTransfer(accountOriginID, accountDestinationID string, amount float64) *Transfer {
	return &Transfer{
		ID:                   NewTransferID(),
		AccountOriginID:      AccountID(accountOriginID),
		AccountDestinationID: AccountID(accountDestinationID),
		Amount:               Float64ToMoney(amount),
		CreatedAt:            time.Now(),
	}
}
