name: Main

on:
  - push

concurrency:
  group: main-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: yokawasa/action-sqlcheck@v1.3.0
        id: sqlcheck
        with:
          post-comment: true
          risk-level: 1
          verbose: true
          token: ${{ secrets.GITHUB_TOKEN }}
          directories: |
            pkg/gateway/datasource/postgres/migrations

      - name: Get output
        run: echo "Issues found in previous step"
        if: steps.sqlcheck.outputs.issue-found
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: make compile

      - name: Test
        run: make test
