name: Release

on:
  workflow_run:
    workflows: [ "Main" ]
    types: [ completed ]
  push:
    branches:
      - main

concurrency:
  group: release-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Install gotest
        run: go install github.com/rakyll/gotest@latest

      - name: Test coverage
        run: gotest -race -failfast -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOVTOKEN }}
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella

      - name: Build
        run: make compile

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "go-springfield-bank"
          heroku_email: "helder.jaspion@gmail.com"
          usedocker: true
