name: Release

on:
  workflow_run:
    workflows: [ "Main" ]
    types: [ completed ]
  push:
    branches:
      - main

concurrency:
  group: release-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  foo:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: make compile

  deploy:
    runs-on: ubuntu-latest
    needs: ["foo"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: make compile

      - name: Test
        run: make test-coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOVTOKEN }}
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "go-springfield-bank"
          heroku_email: "helder.jaspion@gmail.com"
          usedocker: true
